GET http://localhost:3001/api/persons/

###
GET https://sleepy-retreat-90791.herokuapp.com/

###
GET http://localhost:3001/api/persons/2

###
DELETE http://localhost:3001/api/persons/2

###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Farhan Abi",
    "number": "78-38123903"
}
